FROM splunk/splunk:latest

COPY ./inputs.conf /opt/splunk/etc/system/local/inputs.conf
COPY ./props.conf /opt/splunk/etc/system/local/props.conf
COPY ./indexes.conf /opt/splunk/etc/system/local/indexes.conf