FROM python:3.10-slim

# Aggiungi gli strumenti per PostgreSQL
RUN apt-get update && apt-get install -y postgresql-client

# Aggiungi le dipendenze di Python
RUN pip install psycopg2-binary faker

# Copia lo script di seeding
COPY seed.py /docker-entrypoint-initdb.d/seed.py

# Esegui lo script di seeding all'avvio del container
CMD ["python3", "/docker-entrypoint-initdb.d/seed.py"]